base_url = "https://os2x.com"
title = "OS2X"
description = "Operation System & Hyperscale, Zettascale and Yottascale architecture, Future Computing, MLSys, HPC, AI factory"
author = "0xxx"
theme = "academic-workshop"


# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
minify_html = true
build_search_index = false

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]


default_language = "en"

taxonomies = [
	{ name = "tags", feed = true, paginate_by = 10 },
	{ name = "categories", feed = true },
]
# Whether to build a search index to be used later on by a JavaScript library


[markdown]
# highlight_code = false # should be set to false unless the page has code to highlight

[extra]
footer_text = "OS2X" # by default this page adds a small and non-intrusive footer with some text linking to this repository - you can set this to false to remove the footer if you prefer
title = {tagline = "Presenting the", title = "Operation System & Hyperscale Academic Workshop", subtitles = ["For workshops, seminars, and academic events"]} # this contains the header's tagline, title, and list of subtitles, which are displayed in order
banner = {extension = "svg", size = "fixed", fade = true} # this enables a banner image stored in static/banner.svg, with the CSS class bg-fixed: this CSS class is designed for users to set the background image's height and width by overriding CSS - see _main.scss for other classes like bg-contain or bg-cover - the fade option enables a CSS-based fade around the text
buttons = [{name = "OS2X", url = "https://viz.os2x.com"}, {name="GitHub", url="https://github.com/OS2X"}] # creates a list of buttons displayed in order, with links to the URLs
image = {resize = 400, ext = '.jpg'} # this sets the desired size for image resizing, as well as the default extension
list_page_limit = 10 # this sets the default number of items which show up in one page in a list
header_pages = [{name = "Home", url = "/#home"},{name = "Design", url = "/#design"}] # this sets the pages which show up in the navigation menu which gets displayed on mobile devices
button_shortcuts = [{variable = "video", name = "Video"}] # this configuration makes it possible to add a button to a page or section in a less-verbose way, for example by writing video = "/url/to/video" instead of buttons = [{name = "Video", url = "/url/to/video"}]